### ISSUE TITLE
Bulk Dowload Feature

### ISSUE THREAD

**Issue by ryanhausen** [dr-guangtou/unagi#13]
I was looking through the hsc-das-cutout documentation and noticed they have a bulk upload api for space delimited tables (https://hsc-release.mtk.nao.ac.jp/das_cutout/pdr2/manual.html#list-to-upload)

I think this might be a useful addition to your already great project. 
Here is an example table from the documentation:
```
#? rerun      filter    ra       dec       sw     sh  # column descriptor
   pdr2_wide  HSC-G  -1:36:00  00:00:00  2asec  2asec #
   pdr2_wide  HSC-R  -1:36:00  00:00:00  2asec  2asec #
   pdr2_wide  HSC-I  -1:36:00  00:00:00  2asec  2asec # list of coordinates
   pdr2_wide  HSC-Z  -1:36:00  00:00:00  2asec  2asec #
   pdr2_wide  HSC-Y  -1:36:00  00:00:00  2asec  2asec #
```
Assuming the table above was in a file called `sources.txt` we could pull them all at the same time with the following code using the `requests` library:

```python
import requests
from tqdm import tqdm

creds = {
    "user":"your-username-here",
    "secret":"your-password-here"
}

with open("sources.txt", "r") as f:
    # https://stackoverflow.com/a/37573701
    r = requests.post("https://hsc-release.mtk.nao.ac.jp/das_cutout/pdr2/cgi-bin/cutout",
                      files={"list":f}, auth=(creds["user"], creds["secret"]), stream=True)

block_size = 1024
with open("downloaded.tar.gz", "wb") as f:
    for data in tqdm(r.iter_content(block_size), unit='KB', desc=f"Downloading file"):
        f.write(data)
```

**Comment by EiffL** [comment]
@ryanhausen  I implemented a fix to this issue in #14 , can you check if that would do what you want ?

**Comment by ryanhausen** [comment]
I think it looks great!

**Comment by dr-guangtou** [comment]
The issue seems to be solved.
