### ISSUE TITLE
Push unagi to PyPi

### ISSUE THREAD

**Issue by EiffL** [dr-guangtou/unagi#15]
Unagi is awesome, let's make it trivially installable with pip by pushing it to PyPi ;-)

@dr-guangtou Happy to help with this, let me know if I can provide any assistance.

**Comment by dr-guangtou** [comment]
@EiffL I think this is a great idea. I always want to learn how to do that and I think it is time. Let me give it a try first.

To make it like a real package, I think decent documents and testing module are still lacking...I am slowly working on the document part. Let me know if you have any suggestion about these.

**Comment by dr-guangtou** [comment]
@EiffL Ok, just uploaded it to PyPI. 

I tried `pip install` and it seems Ok, but please help me test more. 

Adding your and @AstroJacobLi 's name to the author list.  And update the version number to `0.1.1`....I have no idea how to use the version number...

**Comment by EiffL** [comment]
Fantastic! And it works \o/

This is so cool, check this out:

https://colab.research.google.com/github/dr-guangtou/unagi/blob/master/demo/demo_color_image.ipynb

If you add the following cell right at the top of the notebook:
```
!pip install unagi
```

The whole notebook can be ran in the cloud :-)

**Comment by dr-guangtou** [comment]
@EiffL Nice! I don't know you can do that! 

I should start playing with the colab thing, I heard good things about it!

**Comment by dr-guangtou** [comment]
There are some small things I will update:

@AstroJacobLi mentioned that the pictures do not work on the `PyPI` page, I need to change the format; Also I forgot to put `__version__` in the `__init__.py`.  I will fix these and update in the next "release". 

And I will start working on some documents...

**Comment by EiffL** [comment]
Note that I'm minutes away from implementing #19 which would take care of __version__
