### ISSUE TITLE
unagi import forces the setting of plt.rc('text', usetex=True)

### ISSUE THREAD

**Issue by EiffL** [dr-guangtou/unagi#16]
I like the default `unagi` plotting style but `unagi` may be a little too aggressive in its setting of the rc plot parameters. Simply doing `import unagi` sets the matloplib environment, and in particular sets `plt.rc('text', usetex=True)` here: https://github.com/dr-guangtou/unagi/blob/1f948ce2e77010fb65371b03d1809bfc22c80c43/unagi/plotting.py#L24

I'm runing into an issue when trying to run a code that imports `unagi` internally, in an environment that doesn't have LaTeX installed. My code crashes with:
```
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'
```
(Why not just installing LaTeX? Because I'm running on Google Colab, I have to reinstall the environment every time the notebook is restarted, and installing LaTeX takes a lot of time....)

Here are 2 suggestions:
  - Not importing `plotting` from `__init__.py`, it's not really necessary I don't think...
  - "Hide" the plotting settings in a `unagi.set()` function, in the same way that seaborn does: https://seaborn.pydata.org/generated/seaborn.set.html

Thoughts?

**Comment by dr-guangtou** [comment]
@EiffL I think these are good suggestions. Just pushed my quick first try:

* `plotting` is no longer imported in `__init__.py`
* Now there is a `plotting.setup()` function that deals with all the `matplotlib` configurations. I put most of my previous settings in a `default` style.  Other styles can be added later.  And `latex` font now is an option and the default is `False`.  `plotting.setup(latex=True)` will turn it on. 

I tested this using one demo and it seems to work. Let me know what do you think.

**Comment by dr-guangtou** [comment]
Just realized that I directly pushed to the main branch instead of using a new PR...sorry...

**Comment by EiffL** [comment]
Awesome! This works, I tested it on Colab. Thanks a lot for that!
